---
- hosts: all
  remote_user: vagrant
  become: yes
  tasks:
    - name: actualizamos apt cache
      apt: update_cache=yes

    - name: Instalamos libpq
      apt: name=libpq-dev state=present

    - name: Instalamos git
      apt: name=git state=present

    - name: Instalamos pip
      apt: name=python-pip state=present

    - name: Clonamos repo
      git: repo=https://github.com/cvlolo/IV-Proyecto  dest=home/ubuntu/IV-Proyecto 

    - name: Instalar requirements
      command: pip install -r home/ubuntu/IV-Proyecto/requirements.txt
